{"uid":"fedb31fa8d895f4c","name":"test_forceful_restart_without_data_and_transaction_logs","fullName":"tests.integration.ha_tests.test_self_healing#test_forceful_restart_without_data_and_transaction_logs","historyId":"1ab295315f12ae381caee21d2bb9082a","time":{"start":1716517655629,"stop":1716517959724,"duration":304095},"description":"A forceful restart with deleted data and without transaction logs (forced clone).","descriptionHtml":"<p>A forceful restart with deleted data and without transaction logs (forced clone).</p>\n","status":"failed","statusMessage":"AssertionError: Unable to create continuous_writes table","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 340, in from_call\n    result: Optional[TResult] = func()\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 240, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 501, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 119, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 181, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 99, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 87, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 63, in thread_exception_runtest_hook\n    yield\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 90, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 65, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 849, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 832, in _runtest_for\n    yield\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 883, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 256, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 182, in pytest_runtest_call\n    raise e\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 172, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1772, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 501, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 119, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 181, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 99, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 195, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 532, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/tests/integration/ha_tests/test_self_healing.py\", line 324, in test_forceful_restart_without_data_and_transaction_logs\n    await start_continuous_writes(ops_test, app)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/tests/integration/ha_tests/helpers.py\", line 688, in start_continuous_writes\n    for attempt in Retrying(stop=stop_after_delay(60 * 5), wait=wait_fixed(3), reraise=True):\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/tenacity/__init__.py\", line 347, in __iter__\n    do = self.iter(retry_state=retry_state)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/tenacity/__init__.py\", line 325, in iter\n    raise retry_exc.reraise()\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/tenacity/__init__.py\", line 158, in reraise\n    raise self.last_attempt.result()\n  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\n  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/tests/integration/ha_tests/helpers.py\", line 696, in start_continuous_writes\n    assert action.results[\"result\"] == \"True\", \"Unable to create continuous_writes table\"\nAssertionError: Unable to create continuous_writes table","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"tmp_path_factory","time":{"start":1716514040930,"stop":1716514040931,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop","time":{"start":1716514040930,"stop":1716514040930,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1716514040931,"stop":1716514041070,"duration":139},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"primary_start_timeout","time":{"start":1716515123106,"stop":1716515125185,"duration":2079},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"wal_settings","time":{"start":1716517652434,"stop":1716517655628,"duration":3194},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"continuous_writes","time":{"start":1716517652434,"stop":1716517652434,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1716517652434,"stop":1716517652434,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"wal_settings::finalizer","time":{"start":1716517959725,"stop":1716517988332,"duration":28607},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"continuous_writes::finalizer","time":{"start":1716517988332,"stop":1716518291326,"duration":302994},"status":"failed","statusMessage":"AssertionError: Unable to clear up continuous_writes table\nassert 'False' == 'True'\n  \n  - True\n  + False\n","statusTrace":"  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 302, in finalizer\n    event_loop.run_until_complete(async_finalizer())\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 294, in async_finalizer\n    await gen_obj.__anext__()\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/tests/integration/ha_tests/conftest.py\", line 29, in continuous_writes\n    for attempt in Retrying(stop=stop_after_delay(60 * 5), wait=wait_fixed(3), reraise=True):\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/tenacity/__init__.py\", line 347, in __iter__\n    do = self.iter(retry_state=retry_state)\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/tenacity/__init__.py\", line 325, in iter\n    raise retry_exc.reraise()\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/.tox/integration/lib/python3.10/site-packages/tenacity/__init__.py\", line 158, in reraise\n    raise self.last_attempt.result()\n  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n    return self.__get_result()\n  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n    raise self._exception\n  File \"/home/runner/work/test-runners-github-postgresql-operator/test-runners-github-postgresql-operator/tests/integration/ha_tests/conftest.py\", line 37, in continuous_writes\n    assert action.results[\"result\"] == \"True\", \"Unable to clear up continuous_writes table\"\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"abort_on_fail::0","time":{"start":1716518291327,"stop":1716518291327,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"primary_start_timeout::finalizer","time":{"start":1716519499752,"stop":1716519509774,"duration":10022},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1716519509775,"stop":1716519510474,"duration":699},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1716519510491,"stop":1716519510491,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1716519510491,"stop":1716519510491,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1716519510491,"stop":1716519510491,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"unstable"},{"name":"tag","value":"group(1)"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration.ha_tests"},{"name":"suite","value":"test_self_healing"},{"name":"host","value":"fv-az1245-978"},{"name":"thread","value":"7242-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.ha_tests.test_self_healing"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":5,"broken":23,"skipped":0,"passed":7,"unknown":0,"total":35},"items":[{"uid":"3e1b5c10b5c5083a","reportUrl":"../57//#testresult/3e1b5c10b5c5083a","status":"failed","statusDetails":"AssertionError: Unable to create continuous_writes table","time":{"start":1716431209552,"stop":1716431514360,"duration":304808}},{"uid":"e44a21f194fa52ab","reportUrl":"../56//#testresult/e44a21f194fa52ab","status":"broken","statusDetails":"Exception: ('Expected command %s to succeed instead it failed: %s', 'ls -1 /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_wal/', 1)","time":{"start":1716343003501,"stop":1716343081804,"duration":78303}},{"uid":"ac6858b84702a00e","reportUrl":"../53//#testresult/ac6858b84702a00e","status":"failed","statusDetails":"AssertionError: Unable to create continuous_writes table","time":{"start":1716257546036,"stop":1716257850792,"duration":304756}},{"uid":"2de5a84337ca1d6f","reportUrl":"../51//#testresult/2de5a84337ca1d6f","status":"failed","statusDetails":"AssertionError: Unable to create continuous_writes table","time":{"start":1716084522062,"stop":1716084826713,"duration":304651}},{"uid":"45fe4971e958d9a9","reportUrl":"../50//#testresult/45fe4971e958d9a9","status":"broken","statusDetails":"Exception: ('Expected command %s to succeed instead it failed: %s', 'ls -1 /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_wal/', 1)","time":{"start":1715998889198,"stop":1715998965419,"duration":76221}},{"uid":"cccf12663d59079b","reportUrl":"../49//#testresult/cccf12663d59079b","status":"broken","statusDetails":"Exception: ('Expected command %s to succeed instead it failed: %s', 'ls -1 /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_wal/', 1)","time":{"start":1715911519642,"stop":1715911598865,"duration":79223}},{"uid":"3a502354ed807d3f","reportUrl":"../48//#testresult/3a502354ed807d3f","status":"broken","statusDetails":"Exception: ('Expected command %s to succeed instead it failed: %s', 'ls -1 /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_wal/', 1)","time":{"start":1715825028646,"stop":1715825107203,"duration":78557}},{"uid":"faab1f37dcc876a3","reportUrl":"../47//#testresult/faab1f37dcc876a3","status":"broken","statusDetails":"Exception: ('Expected command %s to succeed instead it failed: %s', 'ls -1 /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_wal/', 1)","time":{"start":1715739787493,"stop":1715739867291,"duration":79798}},{"uid":"1ee54cc73d85b3a4","reportUrl":"../45//#testresult/1ee54cc73d85b3a4","status":"broken","statusDetails":"Exception: ('Expected command %s to succeed instead it failed: %s', 'ls -1 /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_wal/', 1)","time":{"start":1715565581191,"stop":1715565658170,"duration":76979}},{"uid":"11f58de9689f62a9","reportUrl":"../44//#testresult/11f58de9689f62a9","status":"broken","statusDetails":"Exception: ('Expected command %s to succeed instead it failed: %s', 'ls -1 /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_wal/', 1)","time":{"start":1715479388252,"stop":1715479467492,"duration":79240}},{"uid":"c96f32ddcfce1b3f","reportUrl":"../42//#testresult/c96f32ddcfce1b3f","status":"broken","statusDetails":"Exception: ('Expected command %s to succeed instead it failed: %s', 'ls -1 /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_wal/', 1)","time":{"start":1715393074352,"stop":1715393150591,"duration":76239}},{"uid":"beb8bd80e1901e94","reportUrl":"../41//#testresult/beb8bd80e1901e94","status":"passed","time":{"start":1715306559995,"stop":1715306700952,"duration":140957}},{"uid":"9ebfc3b7af933885","reportUrl":"../40//#testresult/9ebfc3b7af933885","status":"broken","statusDetails":"Exception: ('Expected command %s to succeed instead it failed: %s', 'ls -1 /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_wal/', 1)","time":{"start":1715220131057,"stop":1715220207295,"duration":76238}},{"uid":"81625ce2c45015b0","reportUrl":"../39//#testresult/81625ce2c45015b0","status":"broken","statusDetails":"Exception: ('Expected command %s to succeed instead it failed: %s', 'ls -1 /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_wal/', 1)","time":{"start":1715132949680,"stop":1715133028720,"duration":79040}},{"uid":"69e2eaa2f4db6690","reportUrl":"../38//#testresult/69e2eaa2f4db6690","status":"broken","statusDetails":"Exception: ('Expected command %s to succeed instead it failed: %s', 'ls -1 /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_wal/', 1)","time":{"start":1715048034541,"stop":1715048112709,"duration":78168}},{"uid":"a6b7159a9350a01a","reportUrl":"../34//#testresult/a6b7159a9350a01a","status":"passed","time":{"start":1714875983304,"stop":1714876156134,"duration":172830}},{"uid":"a3817896c9ec1765","reportUrl":"../32//#testresult/a3817896c9ec1765","status":"broken","statusDetails":"Exception: ('Expected command %s to succeed instead it failed: %s', 'ls -1 /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_wal/', 1)","time":{"start":1714701875307,"stop":1714701944126,"duration":68819}},{"uid":"da90f4cf774e3301","reportUrl":"../31//#testresult/da90f4cf774e3301","status":"failed","statusDetails":"AssertionError: Unable to create continuous_writes table","time":{"start":1714616014190,"stop":1714616319214,"duration":305024}},{"uid":"7595144bc59e50a5","reportUrl":"../30//#testresult/7595144bc59e50a5","status":"broken","statusDetails":"Exception: ('Expected command %s to succeed instead it failed: %s', 'ls -1 /var/snap/charmed-postgresql/common/var/lib/postgresql/pg_wal/', 1)","time":{"start":1714528587665,"stop":1714528665653,"duration":77988}},{"uid":"4a226503a9f3dcef","reportUrl":"../28//#testresult/4a226503a9f3dcef","status":"passed","time":{"start":1714442257402,"stop":1714442421091,"duration":163689}}]},"tags":["unstable","asyncio","group(1)"]},"source":"fedb31fa8d895f4c.json","parameterValues":[]}